CREATE TABLE [dbo].[Client]
(
	Id		INT IDENTITY (1, 1) NOT NULL,
    Name		VARCHAR (200) NOT NULL,
    Guid		UNIQUEIDENTIFIER NOT NULL,
    Link		VARCHAR (200) NULL,
    Description VARCHAR (MAX) NULL,
    DescriptionHtml VARCHAR (MAX) NULL,
    DescriptionJson VARCHAR (MAX) NULL,
    StreetAddress	VARCHAR (200) NULL,
    City	VARCHAR (100) NULL,
    State		VARCHAR(5) NULL,
    Zipcode	VARCHAR (20) NULL,
    Phone		VARCHAR (20) NULL,
    SupportEmail VARCHAR (100) NULL,
    MarketingEmail VARCHAR (100) NULL,
	--ItemStatusID    INT			  NOT NULL,
	--LayoutConfigurationId INT     NULL, 
	AssetLogoID		INT			  NULL, 
	AssetProfileID	INT			  NULL, 
    CreateUserID    INT NOT NULL,
    CreateDate      DATETIME      NOT NULL,
    UpdateUserID    INT			NULL,
    UpdateDate      DATETIME      NULL,
	
    CONSTRAINT PK_Client PRIMARY KEY CLUSTERED (Id ASC),
    CONSTRAINT UQ_ClientGuid UNIQUE (Guid),
    --CONSTRAINT FK_Client_ItemStatus FOREIGN KEY (ItemStatusID) REFERENCES dbo.ItemStatus (ItemStatusID),
    --CONSTRAINT FK_Client_AssetLogo FOREIGN KEY ([AssetLogoID]) REFERENCES dbo.AssetStore (AssetStoreID),
    --CONSTRAINT FK_Client_AssetProfile FOREIGN KEY ([AssetProfileID]) REFERENCES dbo.AssetStore (AssetStoreID),
	--CONSTRAINT FK_Client_LayoutConfiguration FOREIGN KEY (LayoutConfigurationId) REFERENCES dbo.LayoutConfiguration (LayoutConfigurationID),
	CONSTRAINT FK_Client_CreateUser FOREIGN KEY (CreateUserID) REFERENCES dbo.SecurityUser (ID),
    CONSTRAINT FK_Client_UpdateUser FOREIGN KEY (UpdateUserID) REFERENCES dbo.SecurityUser (ID),
)
