CREATE TABLE [dbo].[Client]
(
	Id				INT IDENTITY (1, 1)	NOT NULL,
    Name			VARCHAR (200)		NOT NULL,
    Guid			UNIQUEIDENTIFIER	NOT NULL,
    Link			VARCHAR (200)	NULL,
    Description		VARCHAR (MAX)	NULL,
    DescriptionHtml VARCHAR (MAX)	NULL,
    DescriptionJson VARCHAR (MAX)	NULL,
    StreetAddress	VARCHAR (200)	NULL,
    City			VARCHAR (100)	NULL,
    State			VARCHAR(5)		NULL,
    Zipcode			VARCHAR (20)	NULL,
    Phone			VARCHAR (20)	NULL,
    SupportEmail	VARCHAR (100)	NULL,
    MarketingEmail	VARCHAR (100)	NULL,
	ItemStatusId    INT			NULL,
	CustomizationId INT			NULL, 
	AssetLogoID		INT			NULL, 
	AssetProfileID	INT			NULL, 
    CreateUserID    INT			NOT NULL,
    CreateDate      DATETIME	NOT NULL,
    UpdateUserID    INT			NULL,
    UpdateDate      DATETIME	NULL,
	
    CONSTRAINT PK_Client PRIMARY KEY CLUSTERED (Id ASC),
    CONSTRAINT UQ_ClientGuid UNIQUE (Guid),
    CONSTRAINT FK_Client_ItemStatus FOREIGN KEY (ItemStatusId) REFERENCES dbo.ItemStatus (Id),
    CONSTRAINT FK_Client_AssetLogo FOREIGN KEY (AssetLogoId) REFERENCES dbo.AssetStore (Id),
    CONSTRAINT FK_Client_AssetProfile FOREIGN KEY (AssetProfileId) REFERENCES dbo.AssetStore (Id),
	CONSTRAINT FK_Client_Customization FOREIGN KEY (CustomizationId) REFERENCES dbo.Customization (Id),
	CONSTRAINT FK_Client_CreateUser FOREIGN KEY (CreateUserId) REFERENCES dbo.SecurityUser (Id),
    CONSTRAINT FK_Client_UpdateUser FOREIGN KEY (UpdateUserId) REFERENCES dbo.SecurityUser (Id),
)
